version: '3'

services:
   zookeeper: 
     image: 'wurstmeister/zookeeper'
     ports: 
      - "2181:2181"
     volumes:
      - "data_dir"     

   kafka:
     image: 'wurstmeister/kafka'
     ports:
      - "9092:9092"
     environment:
       KAFKA_LISTENERS: '192.168.0.106'
       KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'






